apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: false              
  wait: false
  targetNamespace: flux-system             
  patches:
    - target:
        kind: Kustomization
      patch: |-
        - op: add
          path: /spec/decryption
          value:
            provider: sops
        - op: add
          path: /spec/decryption/secretRef
          value:
            name: sops-age # name of sops secret

